[package]
name = "sm-rs-types"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
regress = "0.10.5"
serde = "1.0.228"
serde_json = "1.0.149"
typify = "0.6.0"

[build-dependencies]
serde_json = "1.0.149"
